//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("RestosoftModel", "xc", "categorias_articulos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Restosoft.Entity.categorias_articulos), "grupos_articulos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Restosoft.Entity.grupos_articulos), true)]

#endregion

namespace Restosoft.Entity
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class Restosoft_Entities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto Restosoft_Entities usando la cadena de conexión encontrada en la sección 'Restosoft_Entities' del archivo de configuración de la aplicación.
        /// </summary>
        public Restosoft_Entities() : base("name=Restosoft_Entities", "Restosoft_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto Restosoft_Entities.
        /// </summary>
        public Restosoft_Entities(string connectionString) : base(connectionString, "Restosoft_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto Restosoft_Entities.
        /// </summary>
        public Restosoft_Entities(EntityConnection connection) : base(connection, "Restosoft_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<articulos> articulos
        {
            get
            {
                if ((_articulos == null))
                {
                    _articulos = base.CreateObjectSet<articulos>("articulos");
                }
                return _articulos;
            }
        }
        private ObjectSet<articulos> _articulos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<articulos_compuestos> articulos_compuestos
        {
            get
            {
                if ((_articulos_compuestos == null))
                {
                    _articulos_compuestos = base.CreateObjectSet<articulos_compuestos>("articulos_compuestos");
                }
                return _articulos_compuestos;
            }
        }
        private ObjectSet<articulos_compuestos> _articulos_compuestos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<articulos_compuestos_detalles> articulos_compuestos_detalles
        {
            get
            {
                if ((_articulos_compuestos_detalles == null))
                {
                    _articulos_compuestos_detalles = base.CreateObjectSet<articulos_compuestos_detalles>("articulos_compuestos_detalles");
                }
                return _articulos_compuestos_detalles;
            }
        }
        private ObjectSet<articulos_compuestos_detalles> _articulos_compuestos_detalles;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<categorias_articulos> categorias_articulos
        {
            get
            {
                if ((_categorias_articulos == null))
                {
                    _categorias_articulos = base.CreateObjectSet<categorias_articulos>("categorias_articulos");
                }
                return _categorias_articulos;
            }
        }
        private ObjectSet<categorias_articulos> _categorias_articulos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<cuentas> cuentas
        {
            get
            {
                if ((_cuentas == null))
                {
                    _cuentas = base.CreateObjectSet<cuentas>("cuentas");
                }
                return _cuentas;
            }
        }
        private ObjectSet<cuentas> _cuentas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<cuentas_detalles> cuentas_detalles
        {
            get
            {
                if ((_cuentas_detalles == null))
                {
                    _cuentas_detalles = base.CreateObjectSet<cuentas_detalles>("cuentas_detalles");
                }
                return _cuentas_detalles;
            }
        }
        private ObjectSet<cuentas_detalles> _cuentas_detalles;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<cuentas_temporales> cuentas_temporales
        {
            get
            {
                if ((_cuentas_temporales == null))
                {
                    _cuentas_temporales = base.CreateObjectSet<cuentas_temporales>("cuentas_temporales");
                }
                return _cuentas_temporales;
            }
        }
        private ObjectSet<cuentas_temporales> _cuentas_temporales;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<cuentas_temporales_detalles> cuentas_temporales_detalles
        {
            get
            {
                if ((_cuentas_temporales_detalles == null))
                {
                    _cuentas_temporales_detalles = base.CreateObjectSet<cuentas_temporales_detalles>("cuentas_temporales_detalles");
                }
                return _cuentas_temporales_detalles;
            }
        }
        private ObjectSet<cuentas_temporales_detalles> _cuentas_temporales_detalles;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<empleados> empleados
        {
            get
            {
                if ((_empleados == null))
                {
                    _empleados = base.CreateObjectSet<empleados>("empleados");
                }
                return _empleados;
            }
        }
        private ObjectSet<empleados> _empleados;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<grupos_articulos> grupos_articulos
        {
            get
            {
                if ((_grupos_articulos == null))
                {
                    _grupos_articulos = base.CreateObjectSet<grupos_articulos>("grupos_articulos");
                }
                return _grupos_articulos;
            }
        }
        private ObjectSet<grupos_articulos> _grupos_articulos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<mesas> mesas
        {
            get
            {
                if ((_mesas == null))
                {
                    _mesas = base.CreateObjectSet<mesas>("mesas");
                }
                return _mesas;
            }
        }
        private ObjectSet<mesas> _mesas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<turnos> turnos
        {
            get
            {
                if ((_turnos == null))
                {
                    _turnos = base.CreateObjectSet<turnos>("turnos");
                }
                return _turnos;
            }
        }
        private ObjectSet<turnos> _turnos;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet articulos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToarticulos(articulos articulos)
        {
            base.AddObject("articulos", articulos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet articulos_compuestos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToarticulos_compuestos(articulos_compuestos articulos_compuestos)
        {
            base.AddObject("articulos_compuestos", articulos_compuestos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet articulos_compuestos_detalles. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToarticulos_compuestos_detalles(articulos_compuestos_detalles articulos_compuestos_detalles)
        {
            base.AddObject("articulos_compuestos_detalles", articulos_compuestos_detalles);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet categorias_articulos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTocategorias_articulos(categorias_articulos categorias_articulos)
        {
            base.AddObject("categorias_articulos", categorias_articulos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet cuentas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTocuentas(cuentas cuentas)
        {
            base.AddObject("cuentas", cuentas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet cuentas_detalles. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTocuentas_detalles(cuentas_detalles cuentas_detalles)
        {
            base.AddObject("cuentas_detalles", cuentas_detalles);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet cuentas_temporales. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTocuentas_temporales(cuentas_temporales cuentas_temporales)
        {
            base.AddObject("cuentas_temporales", cuentas_temporales);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet cuentas_temporales_detalles. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTocuentas_temporales_detalles(cuentas_temporales_detalles cuentas_temporales_detalles)
        {
            base.AddObject("cuentas_temporales_detalles", cuentas_temporales_detalles);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet empleados. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToempleados(empleados empleados)
        {
            base.AddObject("empleados", empleados);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet grupos_articulos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTogrupos_articulos(grupos_articulos grupos_articulos)
        {
            base.AddObject("grupos_articulos", grupos_articulos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet mesas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTomesas(mesas mesas)
        {
            base.AddObject("mesas", mesas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet turnos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToturnos(turnos turnos)
        {
            base.AddObject("turnos", turnos);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RestosoftModel", Name="articulos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class articulos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto articulos.
        /// </summary>
        /// <param name="id_articulo">Valor inicial de la propiedad id_articulo.</param>
        public static articulos Createarticulos(global::System.Int32 id_articulo)
        {
            articulos articulos = new articulos();
            articulos.id_articulo = id_articulo;
            return articulos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_articulo
        {
            get
            {
                return _id_articulo;
            }
            set
            {
                if (_id_articulo != value)
                {
                    Onid_articuloChanging(value);
                    ReportPropertyChanging("id_articulo");
                    _id_articulo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_articulo");
                    Onid_articuloChanged();
                }
            }
        }
        private global::System.Int32 _id_articulo;
        partial void Onid_articuloChanging(global::System.Int32 value);
        partial void Onid_articuloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String articulo
        {
            get
            {
                return _articulo;
            }
            set
            {
                OnarticuloChanging(value);
                ReportPropertyChanging("articulo");
                _articulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("articulo");
                OnarticuloChanged();
            }
        }
        private global::System.String _articulo;
        partial void OnarticuloChanging(global::System.String value);
        partial void OnarticuloChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RestosoftModel", Name="articulos_compuestos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class articulos_compuestos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto articulos_compuestos.
        /// </summary>
        /// <param name="id_articulo_compuesto">Valor inicial de la propiedad id_articulo_compuesto.</param>
        public static articulos_compuestos Createarticulos_compuestos(global::System.Byte id_articulo_compuesto)
        {
            articulos_compuestos articulos_compuestos = new articulos_compuestos();
            articulos_compuestos.id_articulo_compuesto = id_articulo_compuesto;
            return articulos_compuestos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte id_articulo_compuesto
        {
            get
            {
                return _id_articulo_compuesto;
            }
            set
            {
                if (_id_articulo_compuesto != value)
                {
                    Onid_articulo_compuestoChanging(value);
                    ReportPropertyChanging("id_articulo_compuesto");
                    _id_articulo_compuesto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_articulo_compuesto");
                    Onid_articulo_compuestoChanged();
                }
            }
        }
        private global::System.Byte _id_articulo_compuesto;
        partial void Onid_articulo_compuestoChanging(global::System.Byte value);
        partial void Onid_articulo_compuestoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> precio
        {
            get
            {
                return _precio;
            }
            set
            {
                OnprecioChanging(value);
                ReportPropertyChanging("precio");
                _precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("precio");
                OnprecioChanged();
            }
        }
        private Nullable<global::System.Decimal> _precio;
        partial void OnprecioChanging(Nullable<global::System.Decimal> value);
        partial void OnprecioChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RestosoftModel", Name="articulos_compuestos_detalles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class articulos_compuestos_detalles : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto articulos_compuestos_detalles.
        /// </summary>
        /// <param name="id_articulo_compuesto_detalle">Valor inicial de la propiedad id_articulo_compuesto_detalle.</param>
        public static articulos_compuestos_detalles Createarticulos_compuestos_detalles(global::System.Byte id_articulo_compuesto_detalle)
        {
            articulos_compuestos_detalles articulos_compuestos_detalles = new articulos_compuestos_detalles();
            articulos_compuestos_detalles.id_articulo_compuesto_detalle = id_articulo_compuesto_detalle;
            return articulos_compuestos_detalles;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte id_articulo_compuesto_detalle
        {
            get
            {
                return _id_articulo_compuesto_detalle;
            }
            set
            {
                if (_id_articulo_compuesto_detalle != value)
                {
                    Onid_articulo_compuesto_detalleChanging(value);
                    ReportPropertyChanging("id_articulo_compuesto_detalle");
                    _id_articulo_compuesto_detalle = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_articulo_compuesto_detalle");
                    Onid_articulo_compuesto_detalleChanged();
                }
            }
        }
        private global::System.Byte _id_articulo_compuesto_detalle;
        partial void Onid_articulo_compuesto_detalleChanging(global::System.Byte value);
        partial void Onid_articulo_compuesto_detalleChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RestosoftModel", Name="categorias_articulos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class categorias_articulos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto categorias_articulos.
        /// </summary>
        /// <param name="id_categoria">Valor inicial de la propiedad id_categoria.</param>
        public static categorias_articulos Createcategorias_articulos(global::System.Byte id_categoria)
        {
            categorias_articulos categorias_articulos = new categorias_articulos();
            categorias_articulos.id_categoria = id_categoria;
            return categorias_articulos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte id_categoria
        {
            get
            {
                return _id_categoria;
            }
            set
            {
                if (_id_categoria != value)
                {
                    Onid_categoriaChanging(value);
                    ReportPropertyChanging("id_categoria");
                    _id_categoria = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_categoria");
                    Onid_categoriaChanged();
                }
            }
        }
        private global::System.Byte _id_categoria;
        partial void Onid_categoriaChanging(global::System.Byte value);
        partial void Onid_categoriaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String categoria
        {
            get
            {
                return _categoria;
            }
            set
            {
                OncategoriaChanging(value);
                ReportPropertyChanging("categoria");
                _categoria = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("categoria");
                OncategoriaChanged();
            }
        }
        private global::System.String _categoria;
        partial void OncategoriaChanging(global::System.String value);
        partial void OncategoriaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RestosoftModel", "xc", "grupos_articulos")]
        public EntityCollection<grupos_articulos> grupos_articulos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<grupos_articulos>("RestosoftModel.xc", "grupos_articulos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<grupos_articulos>("RestosoftModel.xc", "grupos_articulos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RestosoftModel", Name="cuentas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cuentas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto cuentas.
        /// </summary>
        /// <param name="id_cuenta">Valor inicial de la propiedad id_cuenta.</param>
        /// <param name="fecha_creacion">Valor inicial de la propiedad fecha_creacion.</param>
        /// <param name="numero_personas">Valor inicial de la propiedad numero_personas.</param>
        public static cuentas Createcuentas(global::System.Guid id_cuenta, global::System.DateTime fecha_creacion, global::System.Byte numero_personas)
        {
            cuentas cuentas = new cuentas();
            cuentas.id_cuenta = id_cuenta;
            cuentas.fecha_creacion = fecha_creacion;
            cuentas.numero_personas = numero_personas;
            return cuentas;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id_cuenta
        {
            get
            {
                return _id_cuenta;
            }
            set
            {
                if (_id_cuenta != value)
                {
                    Onid_cuentaChanging(value);
                    ReportPropertyChanging("id_cuenta");
                    _id_cuenta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_cuenta");
                    Onid_cuentaChanged();
                }
            }
        }
        private global::System.Guid _id_cuenta;
        partial void Onid_cuentaChanging(global::System.Guid value);
        partial void Onid_cuentaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_creacion
        {
            get
            {
                return _fecha_creacion;
            }
            set
            {
                Onfecha_creacionChanging(value);
                ReportPropertyChanging("fecha_creacion");
                _fecha_creacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_creacion");
                Onfecha_creacionChanged();
            }
        }
        private global::System.DateTime _fecha_creacion;
        partial void Onfecha_creacionChanging(global::System.DateTime value);
        partial void Onfecha_creacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> total_cuenta
        {
            get
            {
                return _total_cuenta;
            }
            set
            {
                Ontotal_cuentaChanging(value);
                ReportPropertyChanging("total_cuenta");
                _total_cuenta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("total_cuenta");
                Ontotal_cuentaChanged();
            }
        }
        private Nullable<global::System.Decimal> _total_cuenta;
        partial void Ontotal_cuentaChanging(Nullable<global::System.Decimal> value);
        partial void Ontotal_cuentaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte numero_personas
        {
            get
            {
                return _numero_personas;
            }
            set
            {
                Onnumero_personasChanging(value);
                ReportPropertyChanging("numero_personas");
                _numero_personas = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numero_personas");
                Onnumero_personasChanged();
            }
        }
        private global::System.Byte _numero_personas;
        partial void Onnumero_personasChanging(global::System.Byte value);
        partial void Onnumero_personasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_termino
        {
            get
            {
                return _fecha_termino;
            }
            set
            {
                Onfecha_terminoChanging(value);
                ReportPropertyChanging("fecha_termino");
                _fecha_termino = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_termino");
                Onfecha_terminoChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_termino;
        partial void Onfecha_terminoChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_terminoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RestosoftModel", Name="cuentas_detalles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cuentas_detalles : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto cuentas_detalles.
        /// </summary>
        /// <param name="id_cuentas_detalles">Valor inicial de la propiedad id_cuentas_detalles.</param>
        public static cuentas_detalles Createcuentas_detalles(global::System.Int32 id_cuentas_detalles)
        {
            cuentas_detalles cuentas_detalles = new cuentas_detalles();
            cuentas_detalles.id_cuentas_detalles = id_cuentas_detalles;
            return cuentas_detalles;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_cuentas_detalles
        {
            get
            {
                return _id_cuentas_detalles;
            }
            set
            {
                if (_id_cuentas_detalles != value)
                {
                    Onid_cuentas_detallesChanging(value);
                    ReportPropertyChanging("id_cuentas_detalles");
                    _id_cuentas_detalles = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_cuentas_detalles");
                    Onid_cuentas_detallesChanged();
                }
            }
        }
        private global::System.Int32 _id_cuentas_detalles;
        partial void Onid_cuentas_detallesChanging(global::System.Int32 value);
        partial void Onid_cuentas_detallesChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RestosoftModel", Name="cuentas_temporales")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cuentas_temporales : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto cuentas_temporales.
        /// </summary>
        /// <param name="id_cuenta_temporal">Valor inicial de la propiedad id_cuenta_temporal.</param>
        public static cuentas_temporales Createcuentas_temporales(global::System.Guid id_cuenta_temporal)
        {
            cuentas_temporales cuentas_temporales = new cuentas_temporales();
            cuentas_temporales.id_cuenta_temporal = id_cuenta_temporal;
            return cuentas_temporales;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id_cuenta_temporal
        {
            get
            {
                return _id_cuenta_temporal;
            }
            set
            {
                if (_id_cuenta_temporal != value)
                {
                    Onid_cuenta_temporalChanging(value);
                    ReportPropertyChanging("id_cuenta_temporal");
                    _id_cuenta_temporal = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_cuenta_temporal");
                    Onid_cuenta_temporalChanged();
                }
            }
        }
        private global::System.Guid _id_cuenta_temporal;
        partial void Onid_cuenta_temporalChanging(global::System.Guid value);
        partial void Onid_cuenta_temporalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_creacion
        {
            get
            {
                return _fecha_creacion;
            }
            set
            {
                Onfecha_creacionChanging(value);
                ReportPropertyChanging("fecha_creacion");
                _fecha_creacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_creacion");
                Onfecha_creacionChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_creacion;
        partial void Onfecha_creacionChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_creacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> total_cuenta
        {
            get
            {
                return _total_cuenta;
            }
            set
            {
                Ontotal_cuentaChanging(value);
                ReportPropertyChanging("total_cuenta");
                _total_cuenta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("total_cuenta");
                Ontotal_cuentaChanged();
            }
        }
        private Nullable<global::System.Decimal> _total_cuenta;
        partial void Ontotal_cuentaChanging(Nullable<global::System.Decimal> value);
        partial void Ontotal_cuentaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> numero_personas
        {
            get
            {
                return _numero_personas;
            }
            set
            {
                Onnumero_personasChanging(value);
                ReportPropertyChanging("numero_personas");
                _numero_personas = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numero_personas");
                Onnumero_personasChanged();
            }
        }
        private Nullable<global::System.Byte> _numero_personas;
        partial void Onnumero_personasChanging(Nullable<global::System.Byte> value);
        partial void Onnumero_personasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_termino
        {
            get
            {
                return _fecha_termino;
            }
            set
            {
                Onfecha_terminoChanging(value);
                ReportPropertyChanging("fecha_termino");
                _fecha_termino = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_termino");
                Onfecha_terminoChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_termino;
        partial void Onfecha_terminoChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_terminoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RestosoftModel", Name="cuentas_temporales_detalles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cuentas_temporales_detalles : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto cuentas_temporales_detalles.
        /// </summary>
        /// <param name="id_cuenta_temporal_detalle">Valor inicial de la propiedad id_cuenta_temporal_detalle.</param>
        public static cuentas_temporales_detalles Createcuentas_temporales_detalles(global::System.Int32 id_cuenta_temporal_detalle)
        {
            cuentas_temporales_detalles cuentas_temporales_detalles = new cuentas_temporales_detalles();
            cuentas_temporales_detalles.id_cuenta_temporal_detalle = id_cuenta_temporal_detalle;
            return cuentas_temporales_detalles;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_cuenta_temporal_detalle
        {
            get
            {
                return _id_cuenta_temporal_detalle;
            }
            set
            {
                if (_id_cuenta_temporal_detalle != value)
                {
                    Onid_cuenta_temporal_detalleChanging(value);
                    ReportPropertyChanging("id_cuenta_temporal_detalle");
                    _id_cuenta_temporal_detalle = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_cuenta_temporal_detalle");
                    Onid_cuenta_temporal_detalleChanged();
                }
            }
        }
        private global::System.Int32 _id_cuenta_temporal_detalle;
        partial void Onid_cuenta_temporal_detalleChanging(global::System.Int32 value);
        partial void Onid_cuenta_temporal_detalleChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RestosoftModel", Name="empleados")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class empleados : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto empleados.
        /// </summary>
        /// <param name="id_empleado">Valor inicial de la propiedad id_empleado.</param>
        public static empleados Createempleados(global::System.Byte id_empleado)
        {
            empleados empleados = new empleados();
            empleados.id_empleado = id_empleado;
            return empleados;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte id_empleado
        {
            get
            {
                return _id_empleado;
            }
            set
            {
                if (_id_empleado != value)
                {
                    Onid_empleadoChanging(value);
                    ReportPropertyChanging("id_empleado");
                    _id_empleado = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_empleado");
                    Onid_empleadoChanged();
                }
            }
        }
        private global::System.Byte _id_empleado;
        partial void Onid_empleadoChanging(global::System.Byte value);
        partial void Onid_empleadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String apellido_paterno
        {
            get
            {
                return _apellido_paterno;
            }
            set
            {
                Onapellido_paternoChanging(value);
                ReportPropertyChanging("apellido_paterno");
                _apellido_paterno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("apellido_paterno");
                Onapellido_paternoChanged();
            }
        }
        private global::System.String _apellido_paterno;
        partial void Onapellido_paternoChanging(global::System.String value);
        partial void Onapellido_paternoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String apellido_materno
        {
            get
            {
                return _apellido_materno;
            }
            set
            {
                Onapellido_maternoChanging(value);
                ReportPropertyChanging("apellido_materno");
                _apellido_materno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("apellido_materno");
                Onapellido_maternoChanged();
            }
        }
        private global::System.String _apellido_materno;
        partial void Onapellido_maternoChanging(global::System.String value);
        partial void Onapellido_maternoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_permiso
        {
            get
            {
                return _id_permiso;
            }
            set
            {
                Onid_permisoChanging(value);
                ReportPropertyChanging("id_permiso");
                _id_permiso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_permiso");
                Onid_permisoChanged();
            }
        }
        private Nullable<global::System.Int32> _id_permiso;
        partial void Onid_permisoChanging(Nullable<global::System.Int32> value);
        partial void Onid_permisoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_nacimiento
        {
            get
            {
                return _fecha_nacimiento;
            }
            set
            {
                Onfecha_nacimientoChanging(value);
                ReportPropertyChanging("fecha_nacimiento");
                _fecha_nacimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_nacimiento");
                Onfecha_nacimientoChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_nacimiento;
        partial void Onfecha_nacimientoChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_nacimientoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_ingreso
        {
            get
            {
                return _fecha_ingreso;
            }
            set
            {
                Onfecha_ingresoChanging(value);
                ReportPropertyChanging("fecha_ingreso");
                _fecha_ingreso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_ingreso");
                Onfecha_ingresoChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_ingreso;
        partial void Onfecha_ingresoChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_ingresoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RestosoftModel", Name="grupos_articulos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class grupos_articulos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto grupos_articulos.
        /// </summary>
        /// <param name="id_grupo">Valor inicial de la propiedad id_grupo.</param>
        /// <param name="categorias_articulos_id_categoria">Valor inicial de la propiedad categorias_articulos_id_categoria.</param>
        public static grupos_articulos Creategrupos_articulos(global::System.Int32 id_grupo, global::System.Byte categorias_articulos_id_categoria)
        {
            grupos_articulos grupos_articulos = new grupos_articulos();
            grupos_articulos.id_grupo = id_grupo;
            grupos_articulos.categorias_articulos_id_categoria = categorias_articulos_id_categoria;
            return grupos_articulos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_grupo
        {
            get
            {
                return _id_grupo;
            }
            set
            {
                if (_id_grupo != value)
                {
                    Onid_grupoChanging(value);
                    ReportPropertyChanging("id_grupo");
                    _id_grupo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_grupo");
                    Onid_grupoChanged();
                }
            }
        }
        private global::System.Int32 _id_grupo;
        partial void Onid_grupoChanging(global::System.Int32 value);
        partial void Onid_grupoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte categorias_articulos_id_categoria
        {
            get
            {
                return _categorias_articulos_id_categoria;
            }
            set
            {
                if (_categorias_articulos_id_categoria != value)
                {
                    Oncategorias_articulos_id_categoriaChanging(value);
                    ReportPropertyChanging("categorias_articulos_id_categoria");
                    _categorias_articulos_id_categoria = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("categorias_articulos_id_categoria");
                    Oncategorias_articulos_id_categoriaChanged();
                }
            }
        }
        private global::System.Byte _categorias_articulos_id_categoria;
        partial void Oncategorias_articulos_id_categoriaChanging(global::System.Byte value);
        partial void Oncategorias_articulos_id_categoriaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String grupo
        {
            get
            {
                return _grupo;
            }
            set
            {
                OngrupoChanging(value);
                ReportPropertyChanging("grupo");
                _grupo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("grupo");
                OngrupoChanged();
            }
        }
        private global::System.String _grupo;
        partial void OngrupoChanging(global::System.String value);
        partial void OngrupoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RestosoftModel", "xc", "categorias_articulos")]
        public categorias_articulos categorias_articulos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<categorias_articulos>("RestosoftModel.xc", "categorias_articulos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<categorias_articulos>("RestosoftModel.xc", "categorias_articulos").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<categorias_articulos> categorias_articulosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<categorias_articulos>("RestosoftModel.xc", "categorias_articulos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<categorias_articulos>("RestosoftModel.xc", "categorias_articulos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RestosoftModel", Name="mesas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class mesas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto mesas.
        /// </summary>
        /// <param name="id_mesa">Valor inicial de la propiedad id_mesa.</param>
        public static mesas Createmesas(global::System.Byte id_mesa)
        {
            mesas mesas = new mesas();
            mesas.id_mesa = id_mesa;
            return mesas;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte id_mesa
        {
            get
            {
                return _id_mesa;
            }
            set
            {
                if (_id_mesa != value)
                {
                    Onid_mesaChanging(value);
                    ReportPropertyChanging("id_mesa");
                    _id_mesa = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_mesa");
                    Onid_mesaChanged();
                }
            }
        }
        private global::System.Byte _id_mesa;
        partial void Onid_mesaChanging(global::System.Byte value);
        partial void Onid_mesaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RestosoftModel", Name="turnos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class turnos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto turnos.
        /// </summary>
        /// <param name="id_turno">Valor inicial de la propiedad id_turno.</param>
        /// <param name="fecha_inicio">Valor inicial de la propiedad fecha_inicio.</param>
        public static turnos Createturnos(global::System.Guid id_turno, global::System.DateTime fecha_inicio)
        {
            turnos turnos = new turnos();
            turnos.id_turno = id_turno;
            turnos.fecha_inicio = fecha_inicio;
            return turnos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id_turno
        {
            get
            {
                return _id_turno;
            }
            set
            {
                if (_id_turno != value)
                {
                    Onid_turnoChanging(value);
                    ReportPropertyChanging("id_turno");
                    _id_turno = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_turno");
                    Onid_turnoChanged();
                }
            }
        }
        private global::System.Guid _id_turno;
        partial void Onid_turnoChanging(global::System.Guid value);
        partial void Onid_turnoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_inicio
        {
            get
            {
                return _fecha_inicio;
            }
            set
            {
                Onfecha_inicioChanging(value);
                ReportPropertyChanging("fecha_inicio");
                _fecha_inicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_inicio");
                Onfecha_inicioChanged();
            }
        }
        private global::System.DateTime _fecha_inicio;
        partial void Onfecha_inicioChanging(global::System.DateTime value);
        partial void Onfecha_inicioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_final
        {
            get
            {
                return _fecha_final;
            }
            set
            {
                Onfecha_finalChanging(value);
                ReportPropertyChanging("fecha_final");
                _fecha_final = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_final");
                Onfecha_finalChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_final;
        partial void Onfecha_finalChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_finalChanged();

        #endregion

    
    }

    #endregion

    
}
